---
- name: jenkins-git-ansible-Redhat
  hosts: prod
  become: yes

  vars:
    source_folder: /ansible/gj
    destin_folder: /var/www/html

  tasks:
  - name: Install Apache
    yum: name=httpd state=latest

  - name: Copy mypage to servers
    copy: src={{ source_folder }}/newindex.html dest={{ destin_folder }}/newindex.html mode=0555
    notify: RestartApache

  - name: Copy pics to servers
    copy: src={{ source_folder }}/pics/{{ item }} dest={{ destin_folder }}/pics/ mode=0555
    loop: 
          - "q.jpg"
          - "qq.jpg"
          - "qqq.bmp"
    notify: RestartApache

  - name: Start Apache
    service: name=httpd state=started enabled=yes

  handlers:
  - name: RestartApache
    service: name=httpd state=restarted




