---
- name: jenkins job for Debian
  hosts: staging
  become: yes

  tasks:
   - name: copy
     copy:
      src: debfile.txt
      dest: /home/engineer/
                                             
   - name: install sysstat
     apt: name=sysstat state=latest
    
   - name: install monit
     apt: name=monit state=latest

   - name: service
     service: name=monit state=restarted enabled=yes
