---
- name: jenkins job for Redhat
  hosts: prod
  become: yes

  tasks:
   - name: copy
     copy:
         src: redfile.txt
         dest: /home/engineer/

   - name: install sysstat
     yum: name=sysstat state=installed
        
   - name: install monit
     yum: name=monit state=installed

   - name: service
     service: name=monit state=restarted enabled=yes


