---
- name: jenkins job for Redhat
  hosts: prod

  tasks:
   - name: copy
     copy:
         src: redfile.txt
         dest: /home/engineer/

   - name: install systat
        yum: name=systat state=installed
        
   - name: install monit
        yum: name=monit state=installed

   - name: service
        service: name=monit state=restarted enabled=yes


